### ISSUE TITLE
抄 vs 複製

### ISSUE THREAD

**Issue by vkedwardli** [Edditoria/notepad-plus-plus-localization-hong-kong#10]
最常用/最常聽一定係 "Copy & Paste" 同埋 「複製貼上」，不過越多英文就越易入魔...

常用/常聽: 抄個檔案去邊度邊度
但係 「抄完再貼」 好似真係冇用+冇聽過?

Example:
「你highlight呢句，copy咗先」
「你highlight呢句，複製咗先」
「你highlight呢句，抄咗先」 ?_?

平時用個「抄」字，好似已經寫埋落去一個實際目標度咁...
所以「抄去剪貼簿」冇問題，但就咁「抄」我真係load咗兩秒都唔係好load到

**Comment by Edditoria** [comment]
個「抄」字係咪太影響？原本係覺得「抄丶剪丶貼丶鏟」一字一動作，反映咗香港人有幾趕頭趕命；另，反正大家都以 Ctrl-X Ctrl-C Ctrl-V 為主。

我諗明你講乜，有時候唔一定要強行保著全文一致，直覺易懂才是重點，我再逐個 review。

**Comment by vkedwardli** [comment]
咁單音節詞又確係廣東話特色，我自己就用開 Copy 個 Cop，e.g.「Cop呢一行」，不過抄fi佬又確實係會用個抄字

呢啲語感問題要等多啲唔同人comment，當然如果想創先河都冇問題

**Comment by Edditoria** [comment]
好喇，經過連日來嘅深思熟慮，我都係決定....用「抄」字。 😆 

- 成個軟件個「抄」字只對應「複製」，冇其它意思；
- 個人偏好 copy > 複製，但係同旁邊嘅 item 會冇咗視覺上嘅平衡感，唔過癮；
- 除咗抄丶剪丶貼丶剷，仲有「抄丶搬」，就一個字。

希望 users 會好快適應到。 😄

**Comment by Edditoria** [comment]
This issue is reviewed in the commit 7d2f782
Consider this issue being solved.

Thanks @vkedwardli 👍
