### ISSUE TITLE
從大方向評介

### ISSUE THREAD

**Issue by bencrox** [Edditoria/notepad-plus-plus-localization-hong-kong#12]
開宗說「如果要求書面語，用返台灣正體中文版咪得囉」，然則，寫得出來，就係書面語，想強調港語和傳統之間有分別，唯有稱舊陣用開的為「傳統書面語」。

有關中英夾雜，呢個問題好攞命。比如我好少聽人講「檔案」「編輯」，但講「Fi佬」，「改下」就多，問題係咁寫只會有更多加人不明白，這也是企圖把港語書面，必然要面對嘅危機。

而且，類似 CloseMore ，又想簡潔又想達意，就有語法障礙，勉強用口語表達，應該係「閂咁啲」，而且唔一定指涉檔案。你喜歡閂咁的目錄（台灣早期都有譯作「卷宗」，問題係大家唔慣，講出來 get 唔到，就算譯得更貼都係嘥氣。）

又像 file-recentFiles ，係咪一定要有個動詞呢？在檔案管理而言，稱之為「近期檔案」、「熱門檔案」都可以，當然，有人會以為係「近期開設」的意思，呢個係習慣問題，正如「最近用過」，也未必如「最近開過」咁準確。

以下我列出自己其餘見解：

* lineOperations :: 據行執行
* comment :: 補註
* autoCompletion :: 自動補完
* 41011 / Exit :: 退出  （散水有各走東西之意）
* 41014 :: 再 load 過   （跟磁碟沒有必然關係）
....
太多了，暫時只是納下眼。

**Comment by Edditoria** [comment]
先謝，一路做心中都不斷疑惑，最後都指返去一個問題：點解要咁寫啫，XXXX咪幾好囉，咁。

其實好多嘢畀你講中，尤其中英夾雜好攞命，唔同嘅 group 又有唔同嘅用語，所以早幾日諗咗個 README「宗旨」好耐好耐，多得幾位大神幫忙，包括你 fb 嘅一句關鍵字：約定俗成，令我思路清晰晒。（後來我又 fine tune咗，約定俗成嘅 priority 唔係最高）

回返你先：

1. 「Fi佬」丶“File”丶「檔案」嘅取捨：先棄「Fi佬」，一來太唔直覺，二來冇人會咁寫 (e.g. Whatsapp)，講都係指 File，但講「檔案」亦好普遍，因為呢個字對 editor 嚟講太重要喇，穩陣取「檔案」，起碼睇得明。取「編輯」同理（編輯器丶新聞編輯丶etc）。
2. `<file-closeMore>`:  「閂咁啲檔案」的確比較準確！
3. `<file-recentFile>` 及相關項目：肯定「最近」比「近期」更啱，你講嘅「最近開過」的確更好 (要再 check 吓係咪要 edit 過嘢先至會入 recent files 清單)。
4. `<edit-lineOperations>` ▶︎ 據行執行 vs 處理呢（幾）行，邊個直覺啲？我都覺得用過一次之後，「據行執行」保持到易懂而且簡潔啲。
5. ”comment“ 關鍵字：未聽過補註，歡迎打臉。
6. `<edit-autoCompletion>` 及相關項目：補完係咪嚟自日文啊？
7. 散水係我特登嘅，有少少玩味而絕唔影響 usage。架撐都係特登嘅，明明有工具可寫，反正架撐就兩項功能。
8. ID “41014” 係譯自英文 “Reload from Disk“，我建議先盡力保留原意，上咗一個版本再逐項逐項同原作者傾，原作者嘅性格你懂的 🤡。另外 “Reload” 亦令我好痛苦 (26 matches)，唔知大家點睇？

Thank you.

**Comment by bencrox** [comment]
本來我 fork 左就諗著大開殺戒的了。就係睇完你呢邊的 issue 先停手，問問先。

**Comment by Edditoria** [comment]
先 close 了，thanks :-)
