### ISSUE TITLE
去 → 佢

### ISSUE THREAD

**Issue by Edditoria** [Edditoria/notepad-plus-plus-localization-hong-kong#15]
Apply 約定俗成，句尾有「去」字，改做寫「佢」

**Comment by vkedwardli** [comment]
語感問題:
閂咗 XXXXXX 佢
如果中間太多字，好似唔順口?
而且如果已經有受詞，好似唔駛用個「佢」字?


|                          |   |
|--------------------------|---|
| 即將會閂咗 Notepad++ 佢  | 👀 |
| 即將會閂咗 Notepad++     | ✅ (未來完成式? )|
| 即將會閂 Notepad++     | ✅ |
|                          |   |
| 剷晒佢                   | ✅ |
| 剷晒                     | ❌ |
|                          |   |
| 閂咗呢個搜尋結果佢       | 👀 |
| 閂咗呢個搜尋結果         | ✅ |
|                          |   |
| 除咗呢個檔案，閂晒其它佢 | ✅ |
| 除咗呢個檔案，閂晒其它   | ❌ |

**Comment by Edditoria** [comment]
Finally resolved in 888a987 yay~
