### ISSUE TITLE
番 → 返

### ISSUE THREAD

**Issue by Edditoria** [Edditoria/notepad-plus-plus-localization-hong-kong#2]
開返出嚟／開番出嚟？
留意返／留意番？

歡迎討論一下，又或者 pull request。

可以搵關鍵字一口氣改，包括 XML 同埋 README.md 檔。

**Comment by AlphaWong** [comment]
好似"返"會好D，因為"番"只係同音。

**Comment by Edditoria** [comment]
我都覺「返」字先至啱￼

**Comment by Edditoria** [comment]
多謝你嘅建議！ :pizza:
