### ISSUE TITLE
「响」->「響」vs「向」vs「喺」?

### ISSUE THREAD

**Issue by Carina-Tang** [Edditoria/notepad-plus-plus-localization-hong-kong#22]
喺Google到search左個「响」字，好似係大陸嗰邊嘅用字？簡體字？
喺香港多數用「響」/「向」，但改做呢兩個又好似睇得有啲辛苦。
所以不如用「喺」？意思同「响」一樣都係表示時間地點。
eg. 42074「**响**檔案總管打開資料夾」 -> 「**喺**檔案總管打開資料夾」

大家點睇？

**Comment by Edditoria** [comment]
係wor！一直寫响，冇留意到添。首先會放棄「向」，會令使用者誤會係有方向／指向嘅意思。

嗱，因為呢個 project 係軟件，所以唔諗地理地點，**諗細啲，例如 mon 嘅畫面**。平日，我會講

- （打電話問檔案）「請問響邊啊？」丶「X你喺邊度啊？」
- （打電話問檔案 again）「響呢度啊」丶「響嗰度啊」丶「咪喺度囉XXXX」

諗返起，我係配合粗口，一係我太多粗口，sor9y

大家平日會點講？

**Comment by Edditoria** [comment]
首先，非常多謝你嘅 issue。 :pizza:

呢個字出現咗 72 次，係重要字眼嚟，我已經 submit 咗去 Notepad++ 嗰邊，所以要急急腳改再 push。簡單講：

- 唔想寫簡體，可免則免；
- 要保持一致，唔好呢度「響」嗰度「喺」
- 先求有再求好，要 ship 喇。

即刻 find and replace 全部改做「喺」，再慢慢 check。

Thx again. :thumbsup:

**Comment by chaaklau** [comment]
`响` 呢度唔係 `響` 嘅簡體，而係 `向` 嘅變調，所以加個口字邊
同 `係` 變 `喺` 同一個道理
不過寫 `喺` 都冇問題

**Comment by Edditoria** [comment]
Issue closed :-)
