### ISSUE TITLE
Language code?

### ISSUE THREAD

**Issue by alexhass** [Edditoria/notepad-plus-plus-localization-hong-kong#24]
What language ID is this translation for? 

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/dd744369(v=ws.10)?redirectedfrom=MSDN
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows

Is this?
`
Chinese (Hong Kong SAR) | zh-HKNote: No longer used. See zh-TW. | 0x0c04 | 3076 -- | -- | -- | --
`

**Comment by Edditoria** [comment]
Yes. What do you want to achieve with this?

In Windows 10, "Hong Kong" region adapts UI in zh-TW (Taiwan), with customized configs in Region name, currency, date/time format, preinstalled input method "速成輸入法", etc.

For installing applications, if zh-TW is not available, we will use en-US (not zh-CN)

For dev tools like Notepad++, we usually use en-US as main language, neither zh-TW nor zh-CN.

I'm also an OEM PC builder. See if I could help.

**Comment by alexhass** [comment]
I‘m the creator of the Notepad++ MSI Setup you can find at https://www.hass.de/content/notepad-msi-package-enterprise-deployment-available

The background why I‘m asking is https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9307 that is stressing me because from time to time new language files appear in npp in an unstructured way with uncommon names. If I know your language file is zh-TW than I can use the language id and can automatically enable your language file for installation in the msi setup.

thanks for your help. If you want to see the MSI setup fully translated I can share the XML file with you and I can add this setup translation, too. Currently there are some strings untranslated.

**Comment by Edditoria** [comment]
Please make sure:

- zh-TW means Taiwan, Traditional Chinese. For Notepad++, please map to "Taiwanese Mandarin": [link to file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/taiwaneseMandarin.xml)
- zh-HK means Hong Kong, Traditional Chinese. For Notepad++, please just map to "English". Yes. English.

I am sorry it makes you stress. But please understand:

- Hong Kong people even don't speak *exactly* in "Yue Chinese". We speak in Cantonese with special tone, with different phrases. i.e., we doesn't share the same culture with (modern) Yue.
- We write in Traditional Chinese. It is different with (modern) Yue Chinese that writes in Simplified Chinese. Therefore, for this common mistake, some app setup display Simplified Chinese for us. This is **so wrong**, and make us angry.

Here is my 2 cents to understand zh-CN/TW/HK:

| Country/Region | Write in | Speak in |
| --- | --- | --- |
| Hong Kong | Traditional Chinese | Cantonese |
| Taiwan | Traditional Chinese | Mandarin |
| China | Simplified Chinese | Mandarin |

:)
