### ISSUE TITLE
hi but with some question

### ISSUE THREAD

**Issue by shenjackyuanjie** [Edditoria/notepad-plus-plus-localization-hong-kong#25]
well if notepad ++ if free(also in speech)
then i can say something like "AMD YES!"
well then i also think that
i can say something like
"**If the U.S. see what did the U.S. do to the U.S. the U.S. must will free the U.S. people from the U.S. government,
_JUST LIKE WHAT DID THEY DO IN THE HONG KONG. RUNENING EVERY POPLE'S LIFE_**"

https://www.bilibili.com/video/BV1ab411E79V
https://www.bilibili.com/video/BV1cJ411274r
so. now who is the one we need to stand with or free with?

did i?

**Comment by Edditoria** [comment]
This issue is irrelevant to this repo. Issue closed.
