### ISSUE TITLE
vscode 而家譯緊粵語版！需要大家幫手～

### ISSUE THREAD

**Issue by laubonghaudoi** [Edditoria/notepad-plus-plus-localization-hong-kong#26]
我哋係@CanCLID ，啱先微軟同意咗幫 vscode 開一個新嘅粵語本地化 https://github.com/microsoft/vscode-loc/issues/204 ，所以我哋準備開始翻譯 vscode 整個粵語版出嚟。想問一下 Notepad++ 嘅各位有冇興趣嚟幫手？我哋想參考一下 Notepad++ 粵語版係點做嘅。唔該晒大家！

**Comment by laubonghaudoi** [comment]
@Edditoria 想問一下，notepad++ 粵語版有冇一個 glossary？即係一個專有名詞總表，我哋想攞嚟參考下，統一好粵語嘅科技詞彙。唔該晒！

**Comment by Edditoria** [comment]
￼不好意思，￼沒有 glossary，在 Notepad++ 的本地化 (localization) 慨念下，我希望圍繞￼在 **香港人** ，而非單純翻譯語言，所以你會見到一些中英夾雜、不遵從全粵語文法、不拘泥於正字古字，又或說，根本不希望被粵文化統一。

或許你可以講成 anti-pattern，可是我希望能保留港式文化，而不是統一詞彙、歸類￼於粵語圈，所以，千萬不要以這個 repo 作凖啊 😉

好奇一問，請問你們團隊的背景是香港人還是所謂的「大中華」？你們會怎樣處理各地的文化差異？

**Comment by laubonghaudoi** [comment]
我哋團隊有晒各個粵語區嘅人，廣東廣西香港美國歐洲東南亞都有，所以我哋嘅目標係將粵語當成一門有國家級地位嘅標準語嚟翻譯，所以個翻譯會儘量避免夾雜官話同英文，亦都唔會特登照顧某一個地區嘅習慣（取各地粵語嘅最大公約數）。即係話，我哋翻譯嘅語言係「粵語標準語」，而唔係純廣州話或者港式粵語或者其他地區粵語。

最尾嘅結果就類似我而家寫嘅呢段話噉，基本上冇夾乜英文亦都冇夾官話，但係各個粵語區嘅人都睇得明。我哋要嘅就係呢種「粵語共同語」嘅效果。

**Comment by laubonghaudoi** [comment]
@Edditoria 我哋將我哋嘅翻譯原則寫咗喺度 https://github.com/CanCLID/vscode-loc/wiki/主頁 ，仲有收集返來嘅詞彙表 https://github.com/CanCLID/vscode-loc/wiki/詞彙術語表 有咩提議都歡迎同我哋講嘅
