### ISSUE TITLE
將「您」改成「你」

### ISSUE THREAD

**Issue by graphemecluster** [Edditoria/notepad-plus-plus-localization-hong-kong#27]
原來粵語冇「您」呢個字，得官話有，所以入面嘅全部「您」要改晒做「你」，麻煩晒！

追記：好似好冇禮貌，唔好意思

**Comment by Edditoria** [comment]
等吓各方面講法先...

呢度寫咗「您」係因為台灣版咁寫，嗰邊似乎都係官話同商業書信係咁，我會去同嗰邊了解吓，可能兩邊都改添。

個「您」字我細個有學過，其它學校嘅朋友都有，做嘢時例如出 newsletter 都主張寫「您」（不過可能因職權而有 bias），所以**係有呢個字嘅**。

至於粵語係點，我注重嘅係香港粵語，而唔會畀大中華歸一化。

我諗考慮點在於：絕大部份軟件都寫「你」，日常都寫「你」為主，咁係咪應該要改呢？好處：**順眼、有利於搜尋**。

先等等，歡迎打**我**面 :)

**Comment by graphemecluster** [comment]
恕我直言，我以前一直都係用開「您」嘅，係最近先改咗呢個習慣。
唔介意嘅話我 @laubonghaudoi

**Comment by littpi-zz** [comment]
根據返 [粵典對於「您」字嘅詮釋](https://words.hk/zidin/%E6%82%A8) ，我覺得如果係想表達對使用者嘅尊重嘅話係可以用。不過對於我黎講，呢個字有種下對上、後輩對前輩嘅意思在內。所以我都贊成用「你」字比較合適。

**Comment by Edditoria** [comment]
@graphemecluster @littpi Thanks!

已改，如無意外，台灣嗰邊都會改 😼
