### ISSUE TITLE
「然後」  > 「跟住」

### ISSUE THREAD

**Issue by bruceyim777** [Edditoria/notepad-plus-plus-localization-hong-kong#5]
㨂字**然後**搵下個（唔記錄關鍵字）
㨂字**然後**搵上個（唔記錄關鍵字）

應該用「跟住」順口D

**Comment by Edditoria** [comment]
「跟著」同「然後」非常相近，想等吓，畀時間大家諗諗，多謝 🙏

Note: Menu 上有 4 個相關 item id: 43014丶43015丶43018丶43049

**Comment by Edditoria** [comment]
思前想後，認為「然後」比「跟著」更加精準冇另一意思，謝謝 issue
