### ISSUE TITLE
Panel 好似順口過「面板」?

### ISSUE THREAD

**Issue by vkedwardli** [Edditoria/notepad-plus-plus-localization-hong-kong#9]
個人語感
btw Panel 有廣東話讀法：「Pan佬」

**Comment by Edditoria** [comment]
好多年前賣 mon 都係講 panel￼，做發佈會都係，唔知而家多唔多人講「面板」？
Notepad++ "panel" 同面板之間，好似真係 panel 真覺啲。（唔知仲有冇其他名）

需要各位 comment 😄

**Comment by 199911** [comment]
直接用panel好過
平時都係中英混用

**Comment by Edditoria** [comment]
基本上可以 confirm 用 panel 呢個字喇，有興趣就整個 PR 過嚟啦
（記得用最新嘅 commit 嚟 pull 啊唔該晒）

注意大細楷；除咗符號之外，中英文字要隔空格：

- Line 171: 細楷P: panel
- Line 172: 細楷P: panel
- Line 191: 大楷P: Panel

i.e. Panel 個字前面加空格，後面唔駛

**Comment by Edditoria** [comment]
多謝你哋嘅建議！ :pizza:
